### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by 00-matt** [f-prime/fist#12]
Hi,

It would be great to get a version number going so that we could track changes that break compatibility with the protocol or database file.

**Comment by f-prime** [comment]
Agreed. How do you suggest we do this? Just add it to the README.md or should we start creating releases?

**Comment by 00-matt** [comment]
We could occasionally tag releases in Git, and have a command to print out the 
version too.

**Comment by f-prime** [comment]
Okay agreed. We have to decide what defines the first version though. At this point almost everything that I wanted done for the basic version is complete. 

- Indexing
- Searching
- Persisting to disk
- Send commands over TELNET

What isn't complete yet that I wanted done before then is deleting entries, and a cli tool. 

So what is your opinion? Should we take what we have and stick the first version number on it (e.g. 0.0.1) or should we wait for the rest of the features? @ioio is currently working on the DELETE command, but I am not sure how long that might take. A CLI tool for the current state fist would be pretty small and easy to develop.

**Comment by 00-matt** [comment]
> So what is your opinion? Should we take what we have and stick the first
> version number on it (e.g. 0.0.1) 

I think it would be fair to call this 0.1.0 or 0.0.1, and then once it's 
feature complete you could move to 1.0.0-beta1 or similar.

**Comment by sonirico** [comment]
Oh, I entered this issue thinking about versioning documents to track document updates :P

**Comment by f-prime** [comment]
@00-matt So I am thinking merging your PR today and adding the version command can be considered 0.1.0. I'll create a release for that. 

@sonirico That is not what he meant but you have me interested with that idea. Care to elaborate on the idea a bit?

**Comment by f-prime** [comment]
Just pushed a change that implements a version command and created the first official release (0.0.1) so I am going to close this issue now.
