### ISSUE TITLE
Database portability

### ISSUE THREAD

**Issue by f-prime** [f-prime/fist#17]
@00-matt pointed out that `uint32_t` should be used instead of `int` when storing integers in the `fist.db` file. Since the size of `int` isn't standard on some systems the `int` could be 2 bytes instead of the currently assumed 4 bytes causing the db file to become corrupted.

So this needs to be fixed.

**Comment by abdollar** [comment]
@f-prime  - you might need to support endianness by swapping bytes or failing gracefully if your systems have different types of CPU's as in big-endian and little endian, though many people would argue little endian has won.

**Comment by f-prime** [comment]
What would be a case where that would be worth doing? As far as I know little endian is used across the board in most cases these days. I don't see fist being used on old legacy CPUs that use big-endian.

**Comment by abdollar** [comment]
You might be correct. It might not be worth supporting or even thinking about at all, like you said, its a very legacy thing. ARM does let you configure it but who cares these days. It might be faster for supporting a wire protocol in network-order(big-endian) but I don't know if its worth it. It might not be worth thinking about at all. I was just thinking of detecting it and exiting but maybe that's not worth the effort either.

**Comment by f-prime** [comment]
I think that it is definitely worth thinking about. Knowing how the software might fail at an edge case is very important I think, even if it's not worth "fixing" right now. 

I agree with your last statement though. A simple solution right now would be to prevent the software from running, or saving the database, if a big-endian CPU is detected.
