### ISSUE TITLE
Persisting data to disk

### ISSUE THREAD

**Issue by ownthink** [f-prime/fist#2]
Is the project continuing?

**Comment by f-prime** [comment]
It is, currently working on the data persistence.

**Comment by ownthink** [comment]
@f-prime full of expectation

**Comment by f-prime** [comment]
@ownthink I just pushed the changes for the data persistence feature. The index gets saved to a file called fist.db which is located in the directory where you start the fist server.

**Comment by ownthink** [comment]
@f-prime This is a very interesting project, I hope to achieve tens of millions of levels of indexing.

**Comment by f-prime** [comment]
With the help of the community I believe we can achieve that.

**Comment by ownthink** [comment]
@f-prime look forward to
