### ISSUE TITLE
Should calloc argument order in hashmap be re-arranged?

### ISSUE THREAD

**Issue by StefanSlehta** [f-prime/fist#22]
The signature of `calloc` looks like this:
`void* calloc (size_t num, size_t size);`
In the current hashmap allocation, `num` of elements depends on the size of the structure, which doesn't seem correct.
https://github.com/f-prime/fist/blob/b0dbed62fdc5b970c67dc475a0e45be91d6fd71e/fist/hashmap.c#L18

**Comment by f-prime** [comment]
That is indeed a bug.. what's more scary is that the tests still pass with it like that and the code seems to work normally. I wonder if this has anything to do with #18 but I doubt it. 

Just pushed the change in https://github.com/f-prime/fist/commit/3ec903b35a8e7630ece9ba989355e87502ff2cf0 

Thanks for catching this.
