### ISSUE TITLE
Server quits unexpectedly 

### ISSUE THREAD

**Issue by f-prime** [f-prime/fist#24]
This is a bug that is also in the release version `0.0.1` and might have something to do with PR 
https://github.com/f-prime/fist/pull/15

The below script pulls the `Beemovie` transcript from Pastebin and attempts to index it. When run, the Fist server stops suddenly with no error message.

I used this code when I was originally testing indexing large files and it worked file (Other than issue #18)

```
import socket
import requests
import string

data = requests.get("https://pastebin.com/raw/Gb02THWc").content.decode().replace("\n", ' ').replace('\r', ' ').replace('  ', ' ').replace("  ", " ").lower()
for p in string.punctuation:
    data = data.replace(p, '')

data = ' '.join(list(filter(None, data.split())))
print(data)

s = socket.socket()
s.connect(("localhost", 5575))
s.send("INDEX beemovie {}\r\n".format(data).encode())
print(s.recv(1024))
s.send(b"SEARCH bee movie\r\n")
print(s.recv(1024))
s.send(b"EXIT\r\n")
```

**Comment by 00-matt** [comment]
I wasn't able to reproduce the crash, however I did break something with #15. Will try and fix now.

**Comment by 00-matt** [comment]
I think that PR #27 should fix it for you as the script you've posted now returns the correct result for me.

**Comment by f-prime** [comment]
This is fixed, I am closing this issue.
