### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by io-ma** [f-prime/fist#26]
- [x] setup sass
- [x] choose fonts
- [x] find favicon
- [x] add code highlighter
- [x] add nav links to github, patreon, slack
- [x] style footer
- [x] add social media icons
- [x] add links to clients
- [x] fix mobile version
- [x] add media queries

**Comment by io-ma** [comment]
https://github.com/io-ma/fist-site

**Comment by f-prime** [comment]
We are live at http://fist-project.com

**Comment by io-ma** [comment]
I have to polish it a bit, will do it asap ( I mean the mobile version). 
Also, make it https https://letsencrypt.org/ @f-prime

**Comment by f-prime** [comment]
Oh true, I will add HTTPS. Mobile does require a bit of work but otherwise everything is great. I just need to edit the content a bit. I also moved `Client Libraries` to its own section, I don't know if you saw.

**Comment by io-ma** [comment]
Just noticed now. Makes sense.
How about I link it in the nav, with a Libraries <a>?
It's more accessible.
