### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by f-prime** [f-prime/fist#28]
Settings such as `max_phrase_length`, `host`, `port, and `buffer_size` should be configurable via a config file.

**Comment by 00-matt** [comment]
What do you think the config file should be like? Something similar to [the OpenSSH config](https://www.ssh.com/ssh/config/) would be easy to write and easy to parse.

**Comment by f-prime** [comment]
Yeah, I was thinking exactly like an OpenSSH config file or Redis conf.

**Comment by WardCunningham** [comment]
It could be a .h file. Then the existing makefile will configure it.

**Comment by f-prime** [comment]
But then people would have to recompile fist every time they make a change to the config file, wouldn't they?

**Comment by 00-matt** [comment]
I think that keeping the config options in a header file would make it impossible to package. Maybe we could keep the default options easily modifiable in a header so that anyone wants to work this way still can.

**Comment by WardCunningham** [comment]
I'm just thinking every time we change max_phrase_length we have to re-index the whole corpus so a few hundred milliseconds to recompile seems like small change. This is just a personal sensitivity of mine when a colleague made a config file to specify where the real config file would be found. We had an amazingly powerful IDE but it couldn't figure out where his numbers came from.

**Comment by f-prime** [comment]
Definitely understand where you're coming from. The problem is that it's just so damn inconvenient especially if you aren't a developer. If you asked me to recompile Redis every time i wanted to make a change to the configuration I'd probably not use Redis. 

Also, in the case of max_phrase_length it also depends on how we define what it means to change the phrase length. I am of the opinion that changing the phrase length of an already established database doesn't require a re-indexing of the entire db. Instead, all data going forward will be indexed using the new max_phrase_length value.
